# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <icd10cm>
  "icd_ch_sec",
  # <icd10cm>
  "icd_code",
  # <icd10cm>
  "icd_description",
  # <icd10cm>
  "icd_sec_code",
  # <msdrg_pdx>
  "pdx_icd",
  # <icd10api>
  # <.multiple_request>
  "V1",
  # <icd10api>
  # <.multiple_request>
  "V2",
  NULL
))
