# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <icd10cm>
  "chapter_sections",
  # <icd10cm>
  "section_codes",
  # <icd10api>
  # <.multiple_request>
  "V1",
  # <icd10api>
  # <.multiple_request>
  "V2",
  NULL
))
